version: '3'
services:
  devops:
    image: prasanthi12332/azurerepo:latest
    ports:
      - "90:80"
    deploy:
      replicas: 3

  aws:
    image: prasanthi123321/datasciencerepo:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3

  datascience:
    image: prasanthi123321/awsrepo:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3

  azure:
    image: prasanthi123321/devopsrepo:latest

    ports:
      - "93:80"
    deploy:
      replicas: 3
